language: ruby
cache: bundler
rvm:
    - 2.1.5
script: bundle exec rake ci
compiler:
    - gcc # for ctags
addons:
    apt:
        packages:
            - vim-gtk
addons:
    apt:
        packages:
            - vim-gtk
before_install:
    - git clone https://github.com/universal-ctags/ctags.git
    - (cd ctags && ./autogen.sh && ./configure --prefix="$HOME" && make -j 4 install)
before_script:
    - "export DISPLAY=:99.0"
    - "export PATH=$PATH:$HOME/bin"
    - "sh -e /etc/init.d/xvfb start"
