version: 2

common: &common
  docker:
    - image: neomake/vims-for-tests:16@sha256:19b0f3f5f9859903e80b5314f57bbfc2d74dbd8300f3b6ed535a627ae80f14cb
  working_directory: ~/repo
  steps:
    - checkout
    - run: make --keep-going testcoverage TEST_VIM=$TEST_VIM
    - run:
        name: Upload coverage results
        command: |
          set -x
          coverage report -m --skip-covered
          coverage xml
          codecov -X search gcov pycov -f coverage.xml --required \
            --name "$CIRCLE_JOB" --flags ${CIRCLE_JOB%%-*} ${CIRCLE_JOB//-/}
          set +x
jobs:
  nvim-master:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-master
  nvim-017:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-v0.1.7
  nvim-020:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-v0.2.0
  nvim-021:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-v0.2.1
  vim-master:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim-master
  vim-8069:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim8069
  vim-74-xenial:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim74-xenial
  vim-74-trusty:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim74-trusty
  vim-73:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim73

  checkqa:
    <<: *common
    steps:
      - checkout
      - run: make --keep-going check check_docker check_lint_diff

workflows:
  version: 2
  test:
    jobs:
      - nvim-021
      - nvim-020
      - nvim-master
      - nvim-017
      - vim-8069
      - vim-master
      - vim-74-xenial
      - vim-74-trusty
      - vim-73
      - checkqa
