language: ruby
matrix:
  include:
    - env: TAGS=
      rvm: 2.3.3
#   - env: TAGS=tcell
#     rvm: 2.2.0

install:
- sudo apt-get update
- sudo apt-get install -y libncurses-dev lib32ncurses5-dev libgpm-dev
- sudo add-apt-repository -y ppa:pi-rho/dev
- sudo apt-add-repository -y ppa:fish-shell/release-2
- sudo apt-get update
- sudo apt-get install -y tmux=1.9a-1~ppa1~p
- sudo apt-get install -y zsh fish

script: |
  make test install &&
  ./install --all &&
  tmux new "ruby test/test_go.rb > out && touch ok" && cat out && [ -e ok ]
