set encoding=utf-8
set guifont=Courier_New:h10:cRUSSIAN
set noswapfile
" Make sure everything works with this weird option
set wildignore=*
function WriteFile(...)
    let r=[]
    if filereadable(s:outfile)
        let r+=readfile(s:outfile, 'b')
    endif
    if type(a:1)==type([])
        let r+=a:1
    else
        let r+=a:000
    endif
    call writefile(r, s:outfile, 'b')
    return ""
endfunction
function PurgeFrawor(str)
    if a:str[-1:] is '<'
        return a:str
    endif
    return substitute(a:str,
                \'^Frawor:\(\%(\\.\|[^:]\)\+:\%(\\.\|[^:]\)\+\):.*', '\1', '')
endfunction
command -nargs=1 -bar W call WriteFile(<q-args>)
let s:outfile=fnamemodify(g:outfile, ':p')
