sudo: false
dist: trusty

language: python

python:
    - 3.5
    - 3.6

install:
    # Install Neovim via Gist
    # https://gist.github.com/lambdalisue/0f461f6a91743895394e63a9a1c65232
    - curl -sL https://gist.githubusercontent.com/lambdalisue/0f461f6a91743895394e63a9a1c65232/raw/install_nvim_for_ci.sh | bash
    - make install

env:
  global:
    - PATH=$HOME/neovim/bin:$PATH
    - PYTEST_ADDOPTS=--cov -rplugin/python3/deoplete

script:
    - make --keep-going test lint
    - coverage report -m --skip-covered
    - coverage xml
    - bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy -X fix -X search -X xcode -f coverage.xml
