---
version: '{build}'
shallow_clone: true
environment:
  matrix:
  - CPU: i386
    ENV: /x86
  - CPU: AMD64
    ENV: /x64
install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" %ENV%'
build_script:
  - nmake -f make_msvc.mak nodebug=1 CPU=%CPU%
artifacts:
  - path: autoload/vimproc_*.dll
    name: vimproc.dll
deploy:
  provider: GitHub
  description: vimproc
  auth_token:
    secure: rKd6JLXUIl3vcA8d0S9w14bl+uvUlZLt0d1M8bmlOh+owQqr5c40+/4ITCNBpHG3
  on:
    appveyor_repo_tag: true
