name: reviewdog

on:
  push:
    branches:
      - main
    paths:
      - "**.vim"
      - ".github/workflows/reviewdog.yml"
  pull_request:
    paths:
      - "**.vim"
      - ".github/workflows/reviewdog.yml"

jobs:
  vimlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-vint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
