name: test

on:
  schedule:
    - cron: "0 7 * * 0"
  push:
    paths:
      - "**.md"
      - "**.ts"
      - "**.vim"
      - ".github/workflows/test.yml"
      - "deno.jsonc"
  pull_request:
    paths:
      - "**.md"
      - "**.ts"
      - "**.vim"
      - ".github/workflows/test.yml"
      - "deno.jsonc"

defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail {0}

jobs:
  check:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        version:
          - "1.x"
    runs-on: ${{ matrix.runner }}
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ matrix.version }}"
      - name: Lint check
        run: deno lint
      - name: Format check
        run: deno fmt --check
      - name: Type check
        run: deno task check

  test:
    strategy:
      matrix:
        runner:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        version:
          - "1.32.x"
          - "1.x"
        host_version:
          - vim: "v9.0.1499"
            nvim: "v0.8.0"
    runs-on: ${{ matrix.runner }}
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ matrix.version }}"
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: "${{ matrix.host_version.vim }}"
      - name: Check Vim
        run: |
          echo ${DENOPS_TEST_VIM}
          ${DENOPS_TEST_VIM} --version
        env:
          DENOPS_TEST_VIM: ${{ steps.vim.outputs.executable }}
      - uses: rhysd/action-setup-vim@v1
        id: nvim
        with:
          neovim: true
          version: "${{ matrix.host_version.nvim }}"
      - name: Check Neovim
        run: |
          echo ${DENOPS_TEST_NVIM}
          ${DENOPS_TEST_NVIM} --version
        env:
          DENOPS_TEST_NVIM: ${{ steps.nvim.outputs.executable }}
      - name: Test
        run: deno task test
        env:
          DENOPS_TEST_DENOPS_PATH: "./"
          DENOPS_TEST_VIM_EXECUTABLE: ${{ steps.vim.outputs.executable }}
          DENOPS_TEST_NVIM_EXECUTABLE: ${{ steps.nvim.outputs.executable }}
        timeout-minutes: 5
      - run: |
          deno coverage --unstable .coverage --lcov > coverage.lcov
      - uses: codecov/codecov-action@v3
        with:
          os: ${{ runner.os }}
          files: ./coverage.lcov
